server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/hz
    username: root
    password: root
    hikari:  # 数据库连接池  类似druid数据库连接池
      maximum-pool-size: 30
      minimum-idle: 10
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

info:
 app.name:  item-service
 company.name:  www.hz.com
 build.artifactId:  $project.artifactId$
 build.version:  $project.version$
logging:
  level:
    com.hz.item.mapper: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名规则